---

image: registry.gitlab.com/vpnbeast/docker-images/docker-base:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - release

# TODO: Implement testing and use in pipeline

release:
  stage: release
  before_script:
    - chmod +x ci-scripts/release.sh
  script:
    - /bin/sh ci-scripts/release.sh master
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch

