---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deployment.name | quote }}
  labels:
    app: {{ .Values.deployment.name | quote }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.deployment.name | quote }}
  template:
    metadata:
      name: {{ .Values.deployment.name | quote }}
      labels:
        app: {{ .Values.deployment.name | quote }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: {{ .Values.deployment.image | quote }}
          {{- if .Values.deployment.variables }}
          env:
          {{- toYaml .Values.deployment.variables | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.ports }}
          ports:
          {{- toYaml .Values.deployment.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.probes -}}
          {{- toYaml .Values.deployment.probes | nindent 10 }}
          {{- end -}}
